# -*- coding: utf-8 -*-
"""aivoicecalls_automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138wIHZQlMKu2-6CIBoM8sOkgDnZP3pdU

#INSTALL PACKAGES
"""

!pip install gspread google-auth-oauthlib google-auth-httplib2 pandas jiwer

!apt-get install -y wkhtmltopdf
!pip install pdfkit

pip install fuzzywuzzy

pip install thefuzz

"""#WER/CER Calculation and Diffs (for transcripts)

"""

import os
import pandas as pd
import gspread
from google.colab import auth, drive
from google.auth import default
import jiwer

print("Authenticating with Google...")

auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

print("\nMounting Google Drive...")
drive.mount('/content/drive')
print("Authentication and Drive mount successful!")

"""Updated script that fixes the file name"""

import os
import gspread
import pdfkit
from google.colab import auth, drive
from google.auth import default
from datetime import datetime
from jiwer import wer, cer
from difflib import ndiff
import difflib

# --- Helper Functions ---
def normalize_text(text: str) -> str:
    """Normalize text for comparison by removing extra spaces and converting to lowercase."""
    if not isinstance(text, str):
        return ""
    return " ".join(text.lower().split())

def create_html_diff(before_text, after_text, output_path):
    """Generates a side-by-side HTML diff file from two strings."""
    before_lines = before_text.splitlines()
    after_lines = after_text.splitlines()
    html_diff = difflib.HtmlDiff(wrapcolumn=80).make_file(
        before_lines,
        after_lines,
        fromdesc='Before (AI Transcript)',
        todesc='After (Revised Transcript)'
    )
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_diff)
    return True

def generate_inline_diff(before_text, after_text):
    """Generates inline text diffs using +/- markup."""
    before_words = before_text.split()
    after_words = after_text.split()
    diff = ndiff(before_words, after_words)

    result_words = []
    for token in diff:
        if token.startswith("- "):
            result_words.append(f"{{-{token[2:]}-}}")  # deletion
        elif token.startswith("+ "):
            result_words.append(f"{{+{token[2:]}+}}")  # insertion
        else:
            result_words.append(token[2:])
    return " ".join(result_words)

def find_transcript_pairs(folder_path, processed_files):
    """Scans for transcript pairs and filters out already processed ones."""
    files = os.listdir(folder_path)
    before_files = [f for f in files if f.endswith('|BEFORE.txt')]
    new_pairs = []
    for before in before_files:
        try:
            base_name, _ = before.rsplit('|', 1)
        except ValueError:
            continue
        after = f"{base_name}|AFTER.txt" # change this to AFTER.txt if the script mess up
        if after in files and after not in processed_files:
            new_pairs.append((os.path.join(folder_path, before), os.path.join(folder_path, after), after, base_name))
    return new_pairs

# --- Main Execution ---
print("Authenticating with Google...")
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)
drive.mount('/content/drive')

CALL_LOGS_FOLDER = "/content/drive/MyDrive/test"
SHEET_NAME = "Transcript Quality Report"

# Google Sheet setup
try:
    sh = gc.open(SHEET_NAME)
    worksheet = sh.sheet1
except gspread.exceptions.SpreadsheetNotFound:
    sh = gc.create(SHEET_NAME)
    worksheet = sh.sheet1
    worksheet.append_row(["Timestamp", "Phone number AI", "Phone number Client", "File name reference", "WER", "CER"])

processed_files = set(worksheet.col_values(4)[1:])
transcript_pairs = find_transcript_pairs(CALL_LOGS_FOLDER, processed_files)

if not transcript_pairs:
    print("\n✅ No new transcripts to process.")
else:
    print(f"\nFound {len(transcript_pairs)} new transcript(s) to process...")

    for before_path, after_path, after_filename, base_name in transcript_pairs:
        with open(before_path, 'r') as f:
            before_text_raw = f.read().strip()
        with open(after_path, 'r') as f:
            after_text_raw = f.read().strip()

        original_text_normalized = normalize_text(before_text_raw)
        revised_text_normalized = normalize_text(after_text_raw)

        wer_value = round(wer(original_text_normalized, revised_text_normalized), 4)
        cer_value = round(cer(original_text_normalized, revised_text_normalized), 4)

        try:
            parts = after_filename.split('|')
            ai_number = parts[0]
            client_number = parts[1]
        except IndexError:
            continue

        worksheet.append_row([
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            ai_number,
            client_number,
            after_filename,
            wer_value,
            cer_value
        ])

        # Inline diff
        diff_text = generate_inline_diff(before_text_raw, after_text_raw)
        diff_txt_path = os.path.join(CALL_LOGS_FOLDER, f"{base_name}|transcript_diffs.txt")
        with open(diff_txt_path, 'w') as f:
            f.write(diff_text)

        # HTML diff
        diff_html_path = os.path.join(CALL_LOGS_FOLDER, f"{base_name}|transcript_diffs.html")
        create_html_diff(before_text_raw, after_text_raw, diff_html_path)

        # PDF conversion
        diff_pdf_path = os.path.join(CALL_LOGS_FOLDER, f"{base_name}|transcript_diffs.pdf")
        pdfkit.from_file(diff_html_path, diff_pdf_path)

        print(f"  - Processed: {after_filename}")
        print(f"    - Inline TXT: {diff_txt_path}")
        print(f"    - HTML Diff: {diff_html_path}")
        print(f"    - PDF Diff: {diff_pdf_path}")

    print("\n✅ All new transcripts, inline diffs, HTML, and PDFs generated.")

"""#Diffs for Structured Data & Evaluation Metrics

NOTE: Make sure you run the pretty print script before running this diff script

https://colab.research.google.com/drive/13rMmUWDRKQrSj2LDB5E4h0W4Q_jkcNrk#scrollTo=6V8WebsN2Lz0
"""

import os
import pandas as pd
import gspread
from google.colab import auth, drive
from google.auth import default
import jiwer

print("Authenticating with Google...")

auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

print("\nMounting Google Drive...")
drive.mount('/content/drive')
print("Authentication and Drive mount successful!")

"""Diff Script"""

import os
import json
import gspread
import difflib
import pdfkit
from google.colab import auth, drive
from google.auth import default
from datetime import datetime

# --- Helper Functions ---

def find_json_pairs(folder_path, processed_files):
    """
    Scans for pretty-printed JSON pairs (dataBEFORE.json and dataAFTER.json)
    and filters out already processed ones.
    """
    files = os.listdir(folder_path)
    before_files = [f for f in files if f.endswith('|dataBEFORE.json')]
    new_pairs = []
    for before in before_files:
        try:
            base_name, _ = before.rsplit('|', 1)
        except ValueError:
            continue
        # Use the base_name to construct the corresponding AFTER filename
        after = f"{base_name}|dataAFTER.json"
        if after in files and after not in processed_files:
            new_pairs.append((
                os.path.join(folder_path, before),
                os.path.join(folder_path, after),
                after, # This will be our reference filename
                base_name
            ))
    return new_pairs

def create_structured_diff(before_data, after_data):
    """
    Performs a deep, recursive comparison of two dictionaries to generate a
    structured diff, identifying the exact path to each change.
    (Fuzzy logic has been removed as requested).
    """
    diff = {
        "added_keys": {},
        "removed_keys": {},
        "modified_values": {}
    }

    # This recursive helper function will do the deep comparison
    def _compare_items(before_item, after_item, path):
        # If items are dictionaries, recurse deeper
        if isinstance(before_item, dict) and isinstance(after_item, dict):
            before_keys = set(before_item.keys())
            after_keys = set(after_item.keys())
            common_keys = before_keys.intersection(after_keys)

            # 1. Find keys added and removed at this level
            added_keys = after_keys - before_keys
            for key in added_keys:
                current_path = ".".join(path + [key])
                diff["added_keys"][current_path] = after_item[key]

            removed_keys = before_keys - after_keys
            for key in removed_keys:
                current_path = ".".join(path + [key])
                diff["removed_keys"][current_path] = before_item[key]

            # 2. Recurse on common keys
            for key in common_keys:
                _compare_items(before_item[key], after_item[key], path + [key])

        # If items are lists, compare them element by element
        elif isinstance(before_item, list) and isinstance(after_item, list):
            if before_item != after_item:
                current_path = ".".join(path)
                diff["modified_values"][current_path] = {
                    "before": before_item,
                    "after": after_item
                }
        # Base case: items are not dicts/lists, compare them directly
        elif before_item != after_item:
            current_path = ".".join(path)
            diff["modified_values"][current_path] = {
                "before": before_item,
                "after": after_item
            }

    _compare_items(before_data, after_data, [])
    return diff


def create_html_diff(before_text, after_text, output_path):
    """Generates a side-by-side HTML diff file from two strings."""
    before_lines = before_text.splitlines()
    after_lines = after_text.splitlines()
    html_diff = difflib.HtmlDiff(wrapcolumn=80).make_file(
        before_lines,
        after_lines,
        fromdesc='Before (AI Structured Data)',
        todesc='After (Revised Structured Data)'
    )
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_diff)
    return True


# --- Main Execution ---
print("Authenticating with Google...")
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)
drive.mount('/content/drive')

# --- Configuration ---
CALL_LOGS_FOLDER = "/content/drive/MyDrive/test"
SHEET_NAME = "Structured Data Diff Log"

# --- Google Sheet Setup ---
try:
    sh = gc.open(SHEET_NAME)
    worksheet = sh.sheet1
except gspread.exceptions.SpreadsheetNotFound:
    sh = gc.create(SHEET_NAME)
    worksheet = sh.sheet1
    worksheet.append_row([
        "Timestamp", "AI Phone Number", "Client Phone Number",
        "File Reference", "Keys Added", "Keys Removed", "Values Modified"
    ])

# --- Processing Logic ---
processed_files = set(worksheet.col_values(4)[1:])
json_pairs = find_json_pairs(CALL_LOGS_FOLDER, processed_files)

if not json_pairs:
    print("\n✅ No new JSON files to process.")
else:
    print(f"\nFound {len(json_pairs)} new JSON pair(s) to process...")

    for before_path, after_path, after_filename, base_name in json_pairs:
        print(f"\nProcessing: {base_name}")
        try:
            with open(before_path, 'r') as f:
                before_json_text = f.read()
                before_data = json.loads(before_json_text)
            with open(after_path, 'r') as f:
                after_json_text = f.read()
                after_data = json.loads(after_json_text)
        except (json.JSONDecodeError, FileNotFoundError) as e:
            print(f"  - Error loading JSON for {base_name}: {e}")
            continue

        # 1. Generate the structured diff
        structured_diff_data = create_structured_diff(before_data, after_data)
        diff_json_path = os.path.join(CALL_LOGS_FOLDER, f"{base_name}|structureddata_diff.json")
        with open(diff_json_path, 'w') as f:
            json.dump(structured_diff_data, f, indent=4)
        print(f"  - Structured Diff JSON created: {diff_json_path}")

        # 2. Generate the visual HTML/PDF diff
        diff_html_path = os.path.join(CALL_LOGS_FOLDER, f"{base_name}|structureddata_diff.html")
        create_html_diff(before_json_text, after_json_text, diff_html_path)
        print(f"  - Visual HTML Diff created: {diff_html_path}")

        try:
            diff_pdf_path = os.path.join(CALL_LOGS_FOLDER, f"{base_name}|structureddata_diff.pdf")
            pdfkit.from_file(diff_html_path, diff_pdf_path)
            print(f"  - Visual PDF Diff created: {diff_pdf_path}")
        except Exception as e:
            print(f"  - Could not create PDF. Ensure wkhtmltopdf is installed. Error: {e}")


        # 3. Update the Google Sheet with summary stats
        try:
            parts = after_filename.split('|')
            ai_number, client_number = parts[0], parts[1]
            # The keys of the diff dictionaries now represent the count
            num_added = len(structured_diff_data["added_keys"])
            num_removed = len(structured_diff_data["removed_keys"])
            num_modified = len(structured_diff_data["modified_values"])

            worksheet.append_row([
                datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                ai_number,
                client_number,
                after_filename,
                num_added,
                num_removed,
                num_modified
            ])
            print(f"  - Updated Google Sheet for: {after_filename}")
        except IndexError:
            print(f"  - Warning: Could not parse filename details for sheet: {after_filename}")
            continue

    print("\n✅ All new diffs generated and log updated.")

"""NOTE: Run the diff script above before running this evaluation script"""

import os
import json
import gspread
from google.colab import auth, drive
from google.auth import default
from datetime import datetime
from jiwer import wer, cer
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload


def get_folder_id(drive_service, folder_name):
    """Finds the ID of a Google Drive folder by its name."""
    query = f"name = '{folder_name}' and mimeType = 'application/vnd.google-apps.folder' and trashed = false"
    response = drive_service.files().list(q=query, spaces='drive', fields='files(id, name)').execute()
    files = response.get('files', [])
    if not files:
        print(f"❌ Error: Could not find a folder named '{folder_name}'. Please check the FOLDER_NAME variable.")
        return None
    # Return the ID of the first folder found with that name
    return files[0].get('id')


def find_json_pairs(folder_path, processed_files):
    """Finds new JSON pairs, filtering out already processed ones."""
    files = os.listdir(folder_path)
    before_files = [f for f in files if f.endswith('|dataBEFORE.json')]
    new_pairs = []
    for before in before_files:
        try:
            base_name, _ = before.rsplit('|', 1)
        except ValueError:
            continue
        if base_name in processed_files:
            continue
        after = f"{base_name}|dataAFTER.json"
        if after in files:
            new_pairs.append((
                os.path.join(folder_path, before),
                os.path.join(folder_path, after),
                base_name
            ))
    return new_pairs

def get_all_keys(data, parent_key='', sep='.'):
    """Recursively gets all keys from a nested dictionary."""
    items = []
    for key, value in data.items():
        new_key = parent_key + sep + key if parent_key else key
        if isinstance(value, dict) and value:
            items.extend(get_all_keys(value, new_key, sep=sep))
        else:
            items.append(new_key)
    return set(items)

def get_all_string_values(data):
    """Recursively gets all string values and concatenates them."""
    all_text = []
    if isinstance(data, dict):
        for value in data.values():
            all_text.append(get_all_string_values(value))
    elif isinstance(data, list):
        for item in data:
            all_text.append(get_all_string_values(item))
    else:
        all_text.append(str(data) if data is not None else "")
    return " ".join(all_text)

def get_value_by_path(data, path):
    """Navigates a dictionary using a dot-separated path."""
    for key in path.split('.'):
        data = data[key]
    return data

def calculate_per_key_metrics(before_data, after_data):
    """
    Calculates WER and CER for only the values that have been modified
    between the two JSON objects.
    """
    before_keys = get_all_keys(before_data)
    after_keys = get_all_keys(after_data)
    common_keys = before_keys.intersection(after_keys)

    per_key_results = {}

    for key_path in common_keys:
        try:
            before_value = get_value_by_path(before_data, key_path)
            after_value = get_value_by_path(after_data, key_path)

            if before_value != after_value:
                before_str = str(before_value)
                after_str = str(after_value)

                per_key_results[key_path] = {
                    "before": before_value,
                    "after": after_value,
                    "WER": round(wer(after_str, before_str), 4),
                    "CER": round(cer(after_str, before_str), 4)
                }
        except KeyError:
            continue

    return per_key_results

# --- Main Execution ---

print("Authenticating with Google...")
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)
drive_service = build('drive', 'v3', credentials=creds)
drive.mount('/content/drive', force_remount=True)

# --- Configuration ---
CALL_LOGS_FOLDER_PATH = "/content/drive/MyDrive/test"

FOLDER_NAME = "test" # Just the name of the final folder
SHEET_NAME = "Structured Data Evaluation"

# --- Google Sheet Setup ---
"""
try:
    sh = gc.open(SHEET_NAME)
    worksheet = sh.sheet1
    print(f"Successfully opened Google Sheet: '{SHEET_NAME}'")
except gspread.exceptions.SpreadsheetNotFound:
    sh = gc.create(SHEET_NAME)
    worksheet = sh.sheet1
    header = [
        "Timestamp", "File Reference", "# Keys in Original", "# Keys in Corrected",
        "Key Precision", "Key Recall", "Value Exact Match Rate",
        "Overall Value WER", "Overall Value CER", "Per-Key Metrics Link"
    ]
    worksheet.append_row(header)
    worksheet.format('A1:J1', {'textFormat': {'bold': True}})
    print(f"Created new Google Sheet with headers: '{SHEET_NAME}'")
    sh.share(None, perm_type='user', role='writer')
"""

# --- Google Sheet Setup ---
try:
    sh = gc.open(SHEET_NAME)
    worksheet = sh.sheet1
    print(f"Successfully opened Google Sheet: '{SHEET_NAME}'")
except gspread.exceptions.SpreadsheetNotFound:
    sh = gc.create(SHEET_NAME)
    worksheet = sh.sheet1
    header = [
        "Timestamp", "File Reference", "# Keys in Original", "# Keys in Corrected",
        "Key Precision", "Key Recall", "Value Exact Match Rate",
        "Overall Value WER", "Overall Value CER", "Per-Key Metrics Link"
    ]
    worksheet.append_row(header)
    worksheet.format('A1:J1', {'textFormat': {'bold': True}})
    print(f"Created new Google Sheet with headers: '{SHEET_NAME}'")

    # Share with current user (so it’s editable)
    sh.share(None, perm_type='user', role='writer')

    # --- NEW: Move the sheet into the CALL_LOGS_FOLDER ---
    try:
        file_id = sh.id  # gspread gives you the sheet's ID
        drive_service.files().update(
            fileId=file_id,
            addParents= target_folder_id,
            removeParents='root',
            fields='id, parents'
        ).execute()
        print(f"Moved Google Sheet '{SHEET_NAME}' into target folder.")
    except Exception as e:
        print(f"⚠️ Could not move Google Sheet into folder: {e}")

# --- Processing Logic ---

target_folder_id = get_folder_id(drive_service, FOLDER_NAME)
if not target_folder_id:
    print("Halting script because target folder could not be found.")
else:
    processed_files = set(worksheet.col_values(2)[1:])
    json_pairs = find_json_pairs(CALL_LOGS_FOLDER_PATH, processed_files)

    if not json_pairs:
        print("\n✅ No new JSON files to evaluate.")
    else:
        print(f"\nFound {len(json_pairs)} new JSON pair(s) to evaluate...")

        for before_path, after_path, base_name in json_pairs:
            print(f"\nEvaluating: {base_name}")
            try:
                with open(before_path, 'r') as f: before_data = json.load(f)
                with open(after_path, 'r') as f: after_data = json.load(f)

                #METRICS FOR EVERYTHING!
                before_keys, after_keys = get_all_keys(before_data), get_all_keys(after_data)
                true_positives = len(before_keys.intersection(after_keys))
                #_____________________________________________________________________________
                key_precision = true_positives / len(after_keys) if len(after_keys) > 0 else 0
                key_recall = true_positives / len(before_keys) if len(before_keys) > 0 else 0
                #_____________________________________________________________________________
                common_keys = before_keys.intersection(after_keys)
                exact_matches = sum(1 for k in common_keys if get_value_by_path(before_data, k) == get_value_by_path(after_data, k))
                value_exact_match_rate = exact_matches / len(common_keys) if common_keys else 0
                before_blob, after_blob = get_all_string_values(before_data), get_all_string_values(after_data)
                overall_wer = wer(after_blob, before_blob)
                overall_cer = cer(after_blob, before_blob)

                per_key_metrics = calculate_per_key_metrics(before_data, after_data)
                metrics_json_path = os.path.join(CALL_LOGS_FOLDER_PATH, f"{base_name}|key_metrics.json")
                with open(metrics_json_path, 'w') as f:
                    json.dump(per_key_metrics, f, indent=4)


                file_metadata = {'name': f"{base_name}|key_metrics.json", 'parents': [target_folder_id]}


                media = MediaFileUpload(metrics_json_path, mimetype='application/json')
                file = drive_service.files().create(body=file_metadata, media_body=media, fields='id').execute()
                metrics_file_link = f"https://drive.google.com/file/d/{file.get('id')}/view"
                print(f"  - Generated and uploaded per-key metrics report.")

                worksheet.append_row([
                    datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    base_name, len(before_keys), len(after_keys),
                    round(key_precision, 4), round(key_recall, 4),
                    round(value_exact_match_rate, 4), round(overall_wer, 4), round(overall_cer, 4),
                    metrics_file_link
                ])
                print(f"  - Successfully calculated and logged all metrics.")

                os.remove(metrics_json_path)

            except Exception as e:
                print(f"  - ❌ Error processing {base_name}: {e}")

    print("\n✅ All new JSON pairs have been evaluated.")

