# -*- coding: utf-8 -*-
"""prettyprintjson.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQ_O4WV4tDdNjAtx6V5rywhIJr0tkhTO

#Installing Packages
"""

!pip install gspread google-auth-oauthlib google-auth-httplib2 pandas jiwer

!apt-get install -y wkhtmltopdf
!pip install pdfkit

pip install fuzzywuzzy

pip install thefuzz

"""#Authenticate"""

import os
import pandas as pd
import gspread
from google.colab import auth, drive
from google.auth import default
import jiwer

print("Authenticating with Google...")

auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

print("\nMounting Google Drive...")
drive.mount('/content/drive')
print("Authentication and Drive mount successful!")

"""#Pretty Print Script"""

import os
import json
import gspread
from google.colab import auth, drive
from google.auth import default
from datetime import datetime

# --- Helper Functions ---

def find_transcript_pairs(folder_path, processed_files):
    """
    Scans for transcript pairs (dataBEFORE.txt and dataAFTER.txt)
    and filters out already processed ones.
    """
    files = os.listdir(folder_path)
    before_files = [f for f in files if f.endswith('|dataBEFORE.txt')]
    new_pairs = []
    for before in before_files:
        try:
            base_name, _ = before.rsplit('|', 1)
        except ValueError:
            continue
        after = f"{base_name}|dataAFTER.txt"
        if after in files and after not in processed_files:
            new_pairs.append((
                os.path.join(folder_path, before),
                os.path.join(folder_path, after),
                after,
                base_name
            ))
    return new_pairs

def pretty_print_json(input_path, output_path):
    """
    Reads a file containing a JSON string, pretty prints it with sorted keys,
    and saves it to a new .json file.
    """
    try:
        with open(input_path, 'r') as f:
            json_string = f.read()
            # Attempt to load the JSON data
            data = json.loads(json_string)
            # Write the pretty-printed JSON to the output file
            with open(output_path, 'w') as out_f:
                json.dump(data, out_f, indent=4, sort_keys=True)
        return True
    except json.JSONDecodeError:
        print(f"  - Error: Could not decode JSON from {input_path}")
        return False
    except Exception as e:
        print(f"  - An unexpected error occurred: {e}")
        return False


# --- Main Execution ---
print("Authenticating with Google...")
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)
drive.mount('/content/drive')

# --- Configuration ---
# The folder in your Google Drive where the .txt files are located.
CALL_LOGS_FOLDER = "/content/drive/MyDrive/test"
# The name of the Google Sheet to update.
SHEET_NAME = "JSON Pretty Print Log"


# --- Google Sheet Setup ---
try:
    sh = gc.open(SHEET_NAME)
    worksheet = sh.sheet1
    print(f"Successfully opened Google Sheet: '{SHEET_NAME}'")
except gspread.exceptions.SpreadsheetNotFound:
    print(f"Spreadsheet '{SHEET_NAME}' not found. Creating a new one.")
    sh = gc.create(SHEET_NAME)
    worksheet = sh.sheet1
    # Set up the header row with timestamp column
    worksheet.append_row([
        "AI Phone Number",
        "Client Phone Number",
        "File Reference",
        "Process Timestamp"  # New column for timestamp
    ])
    # Share the sheet with your email to ensure you have access
    sh.share(creds.service_account_email, perm_type='user', role='writer')


# --- Processing Logic ---
# Get a list of already processed files from the Google Sheet
processed_files = set(worksheet.col_values(3)[1:])  # Column 3 is File Reference
# Find new pairs of transcripts to process
transcript_pairs = find_transcript_pairs(CALL_LOGS_FOLDER, processed_files)

if not transcript_pairs:
    print("\nNo new files have been processed")
else:
    print(f"\nFound {len(transcript_pairs)} new file pair(s) to process...")

    for before_path, after_path, after_filename, base_name in transcript_pairs:
        print(f"\nProcessing pair: {base_name}")

        # --- Pretty Print JSON ---
        before_json_path = os.path.join(CALL_LOGS_FOLDER, f"{base_name}|dataBEFORE.json")
        after_json_path = os.path.join(CALL_LOGS_FOLDER, f"{base_name}|dataAFTER.json")

        # Process the BEFORE file
        if pretty_print_json(before_path, before_json_path):
            print(f"  - Successfully created: {before_json_path}")

        # Process the AFTER file
        if pretty_print_json(after_path, after_json_path):
            print(f"  - Successfully created: {after_json_path}")

        # --- Update Google Sheet ---
        try:
            parts = after_filename.split('|')
            ai_number = parts[0]
            client_number = parts[1]

            # Get current timestamp
            process_timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

            worksheet.append_row([
                ai_number,
                client_number,
                after_filename,  # Using the .txt filename as the reference
                process_timestamp  # Add the timestamp
            ])
            print(f"  - Updated Google Sheet for: {after_filename} at {process_timestamp}")
        except IndexError:
            print(f"  - Warning: Could not parse AI and Client numbers from filename: {after_filename}")
            continue

    print("\n✅ All new JSON files have been pretty-printed and the log has been updated.")

from google.colab import drive
drive.mount('/content/drive')